=== kmariael/XML/XSD.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"> 

    <xsd:element name="CATALOGUE">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="recipe" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="title" type="xsd:string"/>
                            <xsd:element name="prep_time">
                                <xsd:complexType>
                                    <xsd:attribute name="hours" type="xsd:integer" use="required"/>
                                    <xsd:attribute name="minutes" type="xsd:integer" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="cook_time">
                                <xsd:complexType>
                                    <xsd:attribute name="hours" type="xsd:integer" use="required"/>
                                    <xsd:attribute name="minutes" type="xsd:integer" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="difficulty_level" type="xsd:string"/>
                            <xsd:element name="recipe_portions" type="xsd:positiveInteger"/>
                            <xsd:element name="introduction" type="xsd:string"/>
                            <xsd:element name="recipe_category" type="xsd:string" maxOccurs="unbounded"/>
                            <xsd:element name="ingredient" maxOccurs="unbounded">
                                <xsd:complexType mixed="true">
                                    <xsd:attribute name="amount" type="xsd:string" use="optional"/>
                                    <xsd:attribute name="unit" type="xsd:string" use="optional"/>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="preperation">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="title" type="xsd:string"/>
                                        <xsd:element name="introduction" type="xsd:string"/>
                                        <xsd:element name="step" type="xsd:string" maxOccurs="unbounded"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="comment" type="xsd:string" maxOccurs="unbounded"/>
                            <xsd:element name="recommended_recipies">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="title" type="xsd:string"/>
                                        <xsd:element name="recom_recipe" type="xsd:string" maxOccurs="unbounded"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="popular_recipies">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="popular_recipe" type="xsd:string" maxOccurs="unbounded"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>    
</xsd:schema>

=== kmariael/XML/XML_textsfromrecipes.xml
<?xml version="1.0"?>

<CATALOGUE
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="XSD.xsd">

    <recipe>
        <title>Banana bread από την Αργυρώ</title>
        <prep_time hours="0" minutes="10"/>
        <cook_time hours="1" minutes="10"/>
        <difficulty_level>Εύκολη</difficulty_level>
        <recipe_portions>12</recipe_portions>
        <introduction>Banana bread από την Αργυρω Μπαρμπαρίγου. Αυθεντικό και φανταστικό μπανανοψωμο. Δοκιμάστε το απολαυστικό μπανανόψωμο!</introduction>
        <recipe_category>Γλυκά κέικ</recipe_category>
        <recipe_category>Μαγειρεύοντας με την Αργυρώ</recipe_category>
        <recipe_category>Πρωινό</recipe_category>
        <recipe_category>Χριστουγεννιάτικα γλυκά</recipe_category>
        <recipe_category>Ώρα για φαγητό</recipe_category>
        <ingredient amount ="100" unit ="γρ.">καρύδια χοντροκομμένα</ingredient>
        <ingredient amount ="100" unit ="γρ.">γιαούρτι (ή ξινόγαλο)</ingredient>
        <ingredient amount ="125" unit ="γρ.">λιωμένο βούτυρο</ingredient>
        <ingredient amount ="200" unit ="γρ.">καστάνη ζάχαρη (ή μαύρη ζάχαρη)</ingredient>
        <ingredient amount ="220" unit ="γρ.">αλεύρι γ.ο.χ</ingredient>
        <ingredient amount ="1/3" unit ="κ.γλ.">αλάτι</ingredient>
        <ingredient amount ="1/2" unit ="κ.γλ.">κανέλα</ingredient>
        <ingredient amount ="1" unit ="κ.γλ.">υγρή βανίλια</ingredient>
        <ingredient amount ="1" unit ="κ.γλ">σόδα μεγερικής</ingredient>
        <ingredient amount ="2">αυγά χτυπημένα (σε θερμ. δωμ.)</ingredient>
        <ingredient amount ="3">μέτριες ώριμες μπανάνες</ingredient>
        <ingredient amount ="3-4" unit ="σταγόνες">χυμός λεμονιού</ingredient>
        <preperation>
            <title>Αυθεντικό banana bread </title>
            <introduction>Για τη συνταγή banana bread από την Αργυρώ, χρειαζόμαστε όλα τα υλικά να είναι σε θερμοκρασία δωματίου (βούτυρο λιωμένο, αυγά και γιαούρτι). 
            Αν θέλετε να αντικαταστήσετε κάποιο από τα υλικά στο μπανανόψωμο, θα βρείτε παρακάτω αντικαταστάσεις υλικών. Στην συνέχεια για τη συνταγή μας.</introduction>
            <step>Βάζουμε το λεμόνι στο γιαούρτι κι ανακατεύουμε.</step>
            <step>Το αφήνουμε να σταθεί για 5 λεπτά.</step>
            <step>Προθερμαίνουμε το φούρνο στους 170°C βαθμούς στις αντιστάσεις ή στους 160°C βαθμούς στον αέρα.</step>
            <step>Βουτυρώνουμε και αλευρώνουνε μακρόστενη φόρμα του κέικ με διαστάσεις 23×12 εκατ.</step>
            <step>Οι μπανάνες πρέπει να είναι πολύ ώριμες και μαλακές.</step>
            <step>Σε ένα μικρό μπολ, πολτοποιούμε με ένα πιρούνι τις πολύ ώριμες μπανάνες.</step>
            <step>Το αφήνουμε στην άκρη το μίγμα για το banana bread</step>
            <step>Σε ένα μεγάλο μπολ, βάζουμε το λιωμένο και σε θερμοκρασία δωματίου βούτυρο και τη ζάχαρη.</step>
            <step>Με το σύρμα τα ανακατεύουμε να διαλυθεί η ζάχαρη για το μπανανόψωμο μας.</step>
            <step>Προσθέτουμε τα χτυπημένα αυγά, την βανίλια και την κανέλα.</step>
            <step>Με το σύρμα ανακατεύουμε τα υλικά να ομογενοποιηθούν να γίνουν κρέμα.</step>
            <step>Χωριστά σε ένα μπολ ανακατεύουμε το αλεύρι, τη σόδα και το αλάτι με ένα κουτάλι.</step>
            <step>Ρίχνουμε τα στερεά υλικά στο υγρό μείγμα για κέικ.</step>
            <step>Απαλά ανακατεύουμε με το σύρμα. Δεν πρέπει να ανακατεύουμε για πολύ ώρα γιατί θα γίνει πολύ ελαστική η ζύμη του banana bread.</step>
            <step>Τέλος, προσθέτουμε το γιαούρτι, τις πολτοποιημένες μπανάνες και τα καρύδια.</step>
            <step>Απαλά ανακατεύουμε το μείγμα για κέικ για το banana bread.</step>
            <step>Το αδειάζουμε στη φόρμα του κέικ.</step>
            <step>Ψήνουμε το banana bread για 1 ώρα και 10 λεπτά περίπου.</step>
            <step>Αν ψήσετε στις αντιστάσεις, θα βάλετε το banana bread  στην κάτω σχάρα του φούρνου.</step>
            <step>Αν ψήσετε τον αέρα, θα βάλετε το ταψί στη μεσαία σχάρα του φούρνου σας.</step>
            <step>Προς το τέλος του ψησίματος, ίσως χρειαστεί να το σκεπάσετε με αλουμινόχαρτο αν έχει πάρει πολύ χρώμα η επιφάνεια του.</step>
            <step>Αφήνουμε το μπανανόψωμο στον πάγκο να σταθεί για 15 λεπτά και μετά ξεφορμάρουμε σε σχάρα να κρυώσει τελείως.</step>   
        </preperation>
        <comment>Δεν βγάζουμε ποτέ το μείγμα για κέικ από το φούρνο εάν δεν ελέγξουμε αν ψήθηκε σωστά στην καρδιά του. 
                Μπήγουμε τη λάμα από ένα μαχαίρι στην καρδιά του και αν αυτή βγει στεγνή από ζύμη τότε είναι έτοιμο.</comment>
        <comment>Ίσως χρειαστεί λίγα λεπτά επιπλέον ψησίματος μέχρι να στεγνώσει καλά η καρδιά του μπανανόψωμο.</comment>
        <comment>Για το μπανανόψωμο μπορείτε να χρησιμοποιήσετε ό,τι ζάχαρη έχετε ή ό,τι ζάχαρη προτιμάτε. 
                Με την καστανή ή μαύρη ζάχαρη, έχει πιο πλούσια γεύση ενώ με την λευκή ζάχαρη καραμελώνει πιο σωστά.</comment>
        <comment>Τα καρύδια στο banana bread δεν είναι απαραίτητα, εάν θέλετε μπορείτε να τα παραλείψετε. 
                Μπορείτε επίσης να προσθέσετε σοκολάτα σε κομμάτια ή σταγόνες στο μείγμα για κέικ.</comment>
        <comment>Στην Αμερική όπου λατρεύουν το banana bread, το κόβουν σε φέτες και το φρυγανίζουν στην τοστιέρα. 
                Το απολαμβάνουν δηλαδή στο πρωινό τους όπως ένα κανονικό ψωμί με βούτυρο.</comment>
        <comment>Το ξινόγαλα ή το γιαούρτι δίνει φανταστική γεύση και υφή στο banana bread.</comment>
        <comment>Το banana bread διατηρείται σε θερμοκρασία δωματίου για 3 με 4 ημέρες κλεισμένο αεροστεγώς για να μην στεγνώσει.</comment>
        <comment>Διατηρείται επίσης στην κατάψυξη τυλιγμένο πολύ καλά με μεμβράνη για αρκετές εβδομάδες.</comment>
        <comment>Εναλλακτικά αρώματα που μπορείς να δώσεις στο μπανανόψωμο είναι συνδυασμός κανέλας, γαρίφαλου και μοσχοκάρυδου.</comment>
        <comment>Το αφήνουμε να κρυώσει, μπορείς να το περιχύσεις με λιωμένη σοκολάτα.</comment>
        <comment>Με το μείγμα για κέικ του banana bread, μπορείς να φτιάξεις muffins σε θήκες και να τα ψήσεις για περίπου 30 λεπτά.</comment>
        <recommended_recipies>
            <title>Γλυκά ψυγείου</title>
            <recom_recipe>Μπανόφι (banoffee)</recom_recipe>
            <recom_recipe>Τιραμισού</recom_recipe>
            <recom_recipe>Εκμέκ καταΐφι</recom_recipe>
            <recom_recipe>Κορμός Μωσαϊκό</recom_recipe>
            <recom_recipe>Γιαουρτογλυκό του Γιάννου Βαλιάνου</recom_recipe>
        </recommended_recipies>
        <popular_recipies>
            <popular_recipe>Μπιφτέκια αφράτα με πατάτες στο φούρνο</popular_recipe>
            <popular_recipe>Ζύµη για πίτσα (βασική συνταγή)</popular_recipe>
            <popular_recipe>Κρέπες (βασική συνταγή)</popular_recipe>
            <popular_recipe>Γίγαντες στο φούρνο μελωμένοι και πεντανόστιμοι της Αργυρώς Μπαρμπαρίγου</popular_recipe>
            <popular_recipe>Γλυκό ψυγείου</popular_recipe>
        </popular_recipies>
    </recipe>
        
    <recipe>
        <title>Μπιφτέκια κοτόπουλο γεμιστά</title>
        <prep_time hours="0" minutes="5"/>
        <cook_time hours="0" minutes="15"/>
        <difficulty_level>Εύκολη</difficulty_level>
        <recipe_portions>3</recipe_portions>
        <introduction>Μπιφτέκια κοτόπουλο γεμιστά της Αργυρώς. Μιλάμε για τη νοστιμιά! Δαγκώνεις το αφράτο, ζουμερό μπιφτέκι από κιμά κοτόπουλου και τρέχει λιωμένο τυρί. 
        Σερβίρετε με ό,τι σας αρέσει. Πουρέ, πατάτες ή λαχανικά και απολαύστε το ζεστό, μέσα στη σάλτσα του. Σκέτη Μαγεία! Μην αλλάξετε τίποτα. Φανταστική και εύκολη συνταγή σαν της γιαγιάς</introduction>
        <recipe_category>Αγίου Βαλεντίνου - Ρομαντικό δείπνο για δυο</recipe_category>
        <recipe_category>Εύκολα φαγητά για αρχάριους</recipe_category>
        <recipe_category>Εύκολες / Γρήγορες / Οικονομικές</recipe_category>
        <recipe_category>Κιμάς</recipe_category>
        <recipe_category>Κοτόπουλο</recipe_category>
        <recipe_category>Πολυάσχολες μαμάδες</recipe_category>
        <recipe_category>Φαγητά</recipe_category>
        <recipe_category>Ώρα για φαγητό</recipe_category>
        <ingredient>μπιφτέκια</ingredient>
            <ingredient amount="500" unit="γρ.">κιμάς κοτόπουλο</ingredient>
            <ingredient amount="1">μικρό κρεμμύδι ξερό (τριμμένο)</ingredient>
            <ingredient amount="1">μικρή ντομάτα τριμμένη</ingredient>
            <ingredient amount="1" unit="κ.σ.">ελαιόλαδο</ingredient>
            <ingredient amount="1">αυγό</ingredient>
            <ingredient amount="1" unit="κ.γλ.">ξύδι</ingredient>
            <ingredient amount="1" unit="κ.γλ.">μουστάρδα</ingredient>
            <ingredient amount="1" unit="κ.γλ.">ρίγανη</ingredient>
            <ingredient amount="4" unit="γεμάτες κ.σ.">νιφάδες βρώμης</ingredient>
            <ingredient amount="1" unit="κ.σ.">μαϊντανός ψιλοκομμένος</ingredient>
            <ingredient>αλάτι</ingredient>
            <ingredient>φρεσκοτριμμένο πιπέρι</ingredient>
        <ingredient>σάλτσα</ingredient>
            <ingredient amount="1" unit="κ.σ.">ελαιόλαδο</ingredient>
            <ingredient amount="1">σπιτικό ζωμό κότας</ingredient>
            <ingredient amount="1">λεμόνι</ingredient>
        <preperation>
            <title>Μπιφτέκια κοτόπουλο γεμιστά</title>
            <introduction>Αφράτα πεντανόστιμα μπιφτέκια με κιμά κοτόπουλο που θα σας μαγέψουν. Γεμιστά με τυρί που λιώνει σε κάθε μπουκιά. Εύκολη και επαγγελματική συνταγή της Αργυρώς που θα σας θυμίσουν τα μπιφτέκια κοτόπουλου της γιαγιάς. 
            Δείτε τις εναλλακτικές ψησίματος και ψήστε τα στο φούρνο ή το τηγάνι. Σερβίρετε με λαχανικά ή πουρέ και απολαύστε τα ζεστά και ζουμερά!</introduction>
            <step>Βάζουμε τον κιμά για τα μπιφτέκια κοτόπουλο σε ένα μπολ.</step>
            <step>Τρίβουμε το κρεμμύδι στον κιμά και στη συνέχεια τη ντομάτα.</step>
